CREATE TABLE `prospect` (
  `prospect_id` int NOT NULL AUTO_INCREMENT,
  `hash` varchar(32) NOT NULL,
  `prospect_prs_code` varchar(45) DEFAULT NULL,
  `prospect_property_code` int DEFAULT NULL,
  `prospect_status` varchar(10) DEFAULT 'Queue',
  `prospect_email` varchar(255) DEFAULT NULL,
  `prospect_full_name` varchar(255) DEFAULT NULL,
  `prospect_cob` varchar(45) DEFAULT NULL,
  `prospect_dob` varchar(45) DEFAULT NULL,
  `prospect_phone` varchar(45) DEFAULT NULL,
  `prospect_address` varchar(45) DEFAULT NULL,
  `prospect_occupants` varchar(45) DEFAULT NULL,
  `prospect_occupants_over18` varchar(45) DEFAULT NULL,
  `prospect_sector` varchar(45) DEFAULT NULL,
  `prospect_employer` varchar(45) DEFAULT NULL,
  `prospect_job_title` varchar(45) DEFAULT NULL,
  `prospect_income` varchar(45) DEFAULT NULL,
  `prospect_extra` text,
  `prospect_expectedMovein` varchar(45) DEFAULT NULL,
  `prospect_submission_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `prospect_attach_id` varchar(255) DEFAULT NULL,
  `prospect_attach_proofpayment1` varchar(255) DEFAULT NULL,
  `prospect_attach_proofpayment2` varchar(255) DEFAULT NULL,
  `prospect_attach_proofpayment3` varchar(255) DEFAULT NULL,
  `prospect_attach_proofpayment4` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`prospect_id`,`hash`),
  UNIQUE KEY `hash_UNIQUE` (`hash`),
  KEY `prospect_prs_code_idx` (`prospect_prs_code`),
  KEY `prospect_property_code_idx` (`prospect_property_code`),
  CONSTRAINT `prospect_property_code` FOREIGN KEY (`prospect_property_code`) REFERENCES `property` (`property_code`) ON UPDATE CASCADE,
  CONSTRAINT `prospect_prs_code` FOREIGN KEY (`prospect_prs_code`) REFERENCES `prs` (`prs_code`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;